.TH DICTATE-INDICATOR 1 "" "dictate" "User Commands"
.SH NAME
dictate-indicator \- tray icon showing whether dictation is recording
.SH SYNOPSIS
.B dictate-indicator
.RB [ \-\-verbose ]
.SH DESCRIPTION
Follows the state file of
.BR dictate (1)
and shows it in the top bar. Started by the user unit
.BR dictate-indicator.service .
.SH SEE ALSO
.BR dictate (1)
